name: flutter_mixed_example
description: "Demonstrates how to use the flutter_mixed plugin."
publish_to: "none"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_mixed:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
