name: flutter_mixed
description: "FlutterMixed is a Flutter plugin that can quickly mix FlutterFragment int Android applications in the form of View."
version: 0.0.2
homepage: https://github.com/wyq0918dev/flutter_mixed

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wyq0918dev.flutter_mixed
        pluginClass: FlutterMixedPlugin
        dartPluginClass: FlutterMixed
      ios:
        dartPluginClass: FlutterMixed
      linux:
        dartPluginClass: FlutterMixed
      macos:
        dartPluginClass: FlutterMixed
      windows:
        dartPluginClass: FlutterMixed
      web:
        pluginClass: FlutterMixedWeb
        fileName: flutter_mixed_web.dart
