name: flutter_mixed
description: "FlutterMixed is a Flutter plugin that can quickly mix FlutterFragment into existing Android applications in the form of View."
version: 0.0.1
homepage: https://github.com/wyq0918dev/flutter_mixed
repository: https://github.com/wyq0918dev/flutter_mixed
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.wyq0918dev.flutter_mixed
        pluginClass: MixedActivity